### ISSUE TITLE
Code Input Helper incompatible with vi-delphi

### ISSUE THREAD

**Issue by romibi** [cnpack/cnwizards#210]
I'm trying out https://github.com/Tanikai/vi-delphi or rather a fork of it https://github.com/BvdLind/vi-delphi/
It works in Delphi 12.2 without CnPack. But as soon as I enable CnPack, specifically CnPacks Code Input Helper, the vi-delphi-keybindings pollute the source code.

So for example when in vi-delphi's "Normal-Mode" pressing `w` to jump to the end of the word, instead of only jumping to the end of the word the letter `w` also gets inserted at the previous cursor location.

When trying to debug vi-delphi it seemd like CnPack somehow still handles already handled WM_KEYDOWN messages or some VCL CN_BASE + Message from inside TApplication.IsKeyMsg? I did not completely understand what I saw but when i realized it only happens when CnPack is enabled, I gave up further debugging attempts and created this issue entry …

I'm currently using CnPack Version 1.5.0.1209 Build 2024.09.17

**Comment by cnpack** [comment]
Thanks for your report. We spend some time to understand and investigate this conflict.

We guess you mean maybe vi-delphi handled the KeyDown/KeyUp or other Key related message and marked Handled := True, but CnWizards' Input Helper still handle them in spite of Handled True, so the problem comes.

If it's so, we'll try to make some logical adjustment, but not sure whether it works. Could you download attached new DLL, and unzip it to replace original one, and try this problem again?

**Comment by romibi** [comment]
Thank you! Yes this seems to fix the issue.
But I have only tested it quickly, not very intensive.
I have only meetings today and am not working/coding the rest of the week.
I'll try to remember to give an update if there's any additional related issue until the 8. November.

**Comment by cnpack** [comment]
OK, basically it helps a little. Waiting for new information if has.

**Comment by romibi** [comment]
The above linked DLL as well as CnPack Version 1.5.1.1219 Build 2024.11.03 both seem to have fixed the issue.
Thank you!

You can close this issue if you don't need any further information from me.

**Comment by cnpack** [comment]
OK. close it.
